# Generated by Django 3.2.8 on 2021-12-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='category',
            field=models.CharField(choices=[('Champagne', 'Champagne'), ('Cognac', 'Cognac'), ('Pink Wine', 'Pink Wine'), ('Red Wine', 'Red Wine'), ('Rum', 'Rum'), ('White Wine', 'White Wine'), ('Sparkling Wine', 'Sparkling Wine')], max_length=200),
        ),
        migrations.AlterField(
            model_name='market',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
